from typing import Dict

# https://www.economie.gouv.fr/facileco/indices-boursiers

# TODO: Etre en capacité de construire les indices automatiquement
cac_40: Dict = {}
cac_next_20: Dict = {}
sbf_80: Dict = {}
cac_mid_60 = {}
cac_all_tradable = {}
cac_mid_and_small = {}
cac_allshares = {}

sbf_120: Dict = {
    "ACCOR": "AC.PA",
    "AIR FRANCE KLM": "AF.PA",
    "AIR LIQUIDE": "AI.PA",
    "AIRBUS GROUP": "AIR.PA",
    "ALD": "ALD.PA",
    "ALSTOM": "ALO.PA",
    "ALTAREA": "ALTA.PA",
    "ALTEN": "ATE.PA",
    "AMUNDI": "AMUN.PA",
    "APERAM": "APAM.AS",
    "ARCELORMITTAL": "MT.AS",
    "ARKEMA": "AKE.PA",
    "ATOS": "ATO.PA",
    "AXA": "CS.PA",
    "BIC": "BB.PA",
    "BIOMERIEUX": "BIM.PA",
    "BNP PARIBAS": "BNP.PA",
    "BOLLORE": "BOL.PA",
    "BOUYGUES": "EN.PA",
    "BUREAU VERITAS": "BVI.PA",
    "CAPGEMINI": "CAP.PA",
    "CARMILA": "CARM.PA",
    "CARREFOUR": "CA.PA",
    "CASINO GUICHARD PERRACHON": "CO.PA",
    "CGG": "CGG.PA",
    "COFACE": "COFA.PA",
    "COVIVIO": "COV.PA",
    "CREDIT AGRICOLE": "ACA.PA",
    "DANONE": "BN.PA",
    "DASSAULT AVIATION": "AM.PA",
    "DASSAULT SYSTEMES": "DSY.PA",
    "DERICHEBOURG": "DBG.PA",
    "EDENRED": "EDEN.PA",
    "EDF": "EDF.PA",
    "EIFFAGE": "FGR.PA",
    "ELIOR": "ELIOR.PA",
    "ELIS": "ELIS.PA",
    "ENGIE": "ENGI.PA",
    "ERAMET": "ERA.PA",
    "ESSILORLUXOTTICA": "EL.PA",
    "EURAZEO": "RF.PA",
    "EUROAPI": "EAPI.PA",
    "EUROFINS SCIENTIFIC": "ERF.PA",
    "EURONEXT": "ENX.PA",
    "EUTELSAT": "ETL.PA",
    "FAURECIA": "EO.PA",
    "FDJ": "FDJ.PA",
    "FNAC DARTY": "FNAC.PA",
    "GECINA": "GFC.PA",
    "GETLINK": "GET.PA",
    "GROUPE ADP": "ADP.PA",
    "GTT": "GTT.PA",
    "HERMES INTERNATIONAL": "RMS.PA",
    "ICADE": "ICAD.PA",
    "IMERYS": "NK.PA",
    "INTERPARFUMS": "ITP.PA",
    "IPSEN": "IPN.PA",
    "IPSOS": "IPS.PA",
    "JCDECAUX": "DEC.PA",
    "KERING": "KER.PA",
    "KLEPIERRE": "LI.PA",
    "KORIAN": "KORI.PA",
    "LEGRAND": "LR.PA",
    "L'OREAL": "OR.PA",
    "LVMH": "MC.PA",
    "M6 METROPOLE TELEVISION": "MMT.PA",
    "MAISONS DU MONDE": "MDM.PA",
    "MCPHY ENERGY": "MCPHY.PA",
    "MERCIALYS": "MERY.PA",
    "MICHELIN": "ML.PA",
    "NEOEN": "NEOEN.PA",
    "NEXANS": "NEX.PA",
    "NEXITY": "NXI.PA",
    "ORANGE": "ORA.PA",
    "ORPEA": "ORP.PA",
    "OVH": "OVH.PA",
    "PERNOD RICARD": "RI.PA",
    "PLASTIC OMNIUM": "POM.PA",
    "PUBLICIS": "PUB.PA",
    "QUADIENT": "QDT.PA",
    "REMY COINTREAU": "RCO.PA",
    "RENAULT": "RNO.PA",
    "REXEL": "RXL.PA",
    "RUBIS": "RUI.PA",
    "SAFRAN": "SAF.PA",
    "SAINT-GOBAIN": "SGO.PA",
    "SANOFI": "SAN.PA",
    "SARTORIUS STEDIM BIOTECH": "DIM.PA",
    "SCHNEIDER ELECTRIC": "SU.PA",
    "SCOR SE": "SCR.PA",
    "SEB": "SK.PA",
    "SES": "SESG.PA",
    "SOCIETE GENERALE": "GLE.PA",
    "SODEXO": "SW.PA",
    "SOITEC": "SOI.PA",
    "SOLUTIONS 30": "S30.PA",
    "SOLVAY": "SOLB.BR",
    "SOPRA STERIA GROUP": "SOP.PA",
    "SPIE": "SPIE.PA",
    "STELLANTIS": "STLA.PA",
    "STMICROELECTRONICS": "STM.PA",
    "TECHNIP ENERGIES": "TE.PA",
    "TELEPERFORMANCE": "TEP.PA",
    "TF1": "TFI.PA",
    "THALES": "HO.PA",
    "TOTALENERGIES": "TTE.PA",
    "TRIGANO": "TRI.PA",
    "UBISOFT": "UBI.PA",
    "UNIBAIL-RODAMCO-WESTFIELD": "URW.AS",
    "VALEO": "FR.PA",
    "VALLOUREC": "VK.PA",
    "VALNEVA SE": "VLA.PA",
    "VEOLIA ENVIRONNEMENT": "VIE.PA",
    "VERALLIA": "VRLA.PA",
    "VINCI": "DG.PA",
    "VIRBAC": "VIRP.PA",
    "VIVENDI SE": "VIV.PA",
    "WENDEL": "MF.PA",
    "WORLDLINE": "WLN.PA",
}
